# Generated by Django 6.0.3 on 2026-04-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(choices=[('UNSELECTED', 'Unselected'), ('PAY_NOW', 'Pay Now'), ('PAY_AT_CLINIC', 'Pay At Clinic')], default='UNSELECTED', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PENDING_ONLINE', 'Pending Online Payment'), ('TO_BE_PAID_AT_CLINIC', 'To Be Paid At Clinic'), ('PAID', 'Paid')], default='UNPAID', max_length=24),
        ),
    ]
